#!/bin/bash -l
#$ -N bloomboard_ens
#$ -t 1-4
#$ -pe omp 8
#$ -l mem_per_core=4G
#$ -l h_rt=04:00:00
#$ -l buyin
#$ -j y
#$ -o /projectnb/dietzelab/cwebb16/BloomBoard/logs/
#$ -M cwebb16@bu.edu
#$ -m e

mkdir -p /projectnb/dietzelab/cwebb16/BloomBoard/logs

module load R/4.4.0

source /projectnb/dietzelab/cwebb16/FRP_Models_repo/FRP_Run/.env.sh

cd /projectnb/dietzelab/cwebb16/BloomBoard
YEARS=(2021 2022 2023 2024)
YEAR=${YEARS[$((SGE_TASK_ID - 1))]}
Rscript run_ensemble.R ${YEAR}-01-01 ${YEAR}-12-31
