name: BloomBoard Daily Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  r-job:
    runs-on: ubuntu-latest

    env:
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}

    container: eco4cast/rocker-neon4cast:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install R packages
        run: |
          Rscript -e 'options(repos=c(CRAN="https://cloud.r-project.org"))'
          Rscript -e 'pkgs <- c("yaml","httr","readr","dplyr","lubridate","aws.s3","ranger","foreach","doParallel"); need <- pkgs[!pkgs %in% rownames(installed.packages())]; if(length(need)) install.packages(need, Ncpus = 2)'

      - name: Run BloomBoard
        run: |
          Rscript run.R

      - name: Ping healthcheck
        run: |
          curl -fsS -m 10 --retry 5 https://hc-ping.com/34e8099e-e13c-404b-9821-7e26111728c8
